<a href="https://colab.research.google.com/github/Gus-22/Gus-22/blob/main/3_sistemas_triangulares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. Resolução de sistemas lineares <br><br>

Na aula passada vimos:

- como trabalhar com sistemas lineares a partir de matrizes e vetores, na forma $Ax=b$;
- como interpretar geometricamente as equações e o conjunto solução do sistema;
- como verificar se um vetor $x$ é solução de um sistema linear;
- como verificar se um sistema $n\times n$ tem solução única através da matriz inversa $A^{-1}$.

<br>

**Hoje veremos como de fato determinar o conjunto solução de sistemas lineares.**

<br><br>

***

<br>

# Utilizando diretamente NumPy <br>

Sistemas lineares são uma classe importante de problemas e obviamente há muitas funções prontas nas bibliotecas em Python para resolvê-los diretamente.

Uma delas é a função `solve`, do módulo `linalg` na biblioteca NumPy.

<br>

### Exemplo 1:<br>

Vamos resolver o sistema linear

$$\begin{cases}
    x_1 + 3x_2 -2x_3 = -22\\
    2x_1 -x_2 + 3x_3 = -9\\
    -2x_2 + 4x_3= -2
\end{cases}. $$

Começamos definindo a sua matriz de coeficientes $A$ e o vetor de termos independentes $b$ como *arrays*.

In [ ]:
import numpy as np

A = np.array([[1, 3, -2], [2, -1, 3], [0, -2, 4]])
b = np.array([-22, -9, -2])

A seguir, basta aplicar a função, que requer $A$ e $b$ como entradas.

In [ ]:
# função que calcula a resposta da matriz A com termos independentes b
x = np.linalg.solve(A, b)

print(x)

[ -1. -11.  -6.]


Faça a prova real abaixo:

In [ ]:
# a função resolve o problema, já que fazendo A * x = b
real = np.dot(A, x)

print(real)

[-22.  -9.  -2.]


<br><br>

Nesse caso, vimos que a solução é única. Fica a pergunta:

> **E quando o sistema não tem solução? Ou possui infinitas soluções?**

<br>

***

## Exercício 1:<br>

(a) Defina uma matriz $A$ e um vetor $b$ abaixo tais que o sistema $Ax=b$ não possua solução ou possua infinitas soluções, justificando por que isso acontece:

$$
A =
\begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1
\end{bmatrix}
$$

$$
b =
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

**Justificativa:** não tem soluções, já que x + y + z = 1, portanto x + y + z não pode ser = 2 e = 3 também

<br>

(b) Utilize o comando `np.linalg.solve` para resolver o sistema acima e veja o que acontece.

In [ ]:
# O sistema não tem solução, portanto dará erro, já que o sistem não pode achar soluções que não existem

A = np.array(([1, 1, 1],[1, 1, 1],[1, 1, 1]))
b = np.array([1, 2, 3])

respos = np.linalg.solve(A, b)
print(respos)

<br>

***
<br>

> Ou seja, exceto quando a solução é única, a função `np.linalg.solve` não é tão útil assim.
<br>

> Mas mesmo quando podemos usá-la, **qual a ideia por trás desse comando**? É isso que vamos tentar responder agora.

<br>

***

# Sistemas triangulares <br>

Chamamos um sistema linear de **triangular** quando a sua matriz de coeficientes $A$ for uma **matriz triangular superior** ou **triangular inferior**, isto, tiver todos os elementos acima (ou abaixo) da diagonal principal iguais a zero.

Sistemas desse tipo são simples pois **uma das variáveis já aparece explicitada** e com ela podemos determinar as outras.

<br><br>

## Exemplo 2: <br>

Considere o sistema

$$
\begin{cases}
-3x_0 + &4x_1 -&x_2 = 4 \\
&3x_1 + &2x_2 = -1 \\
&&3x_2 = -15
\end{cases}.
$$

Note que a matriz de coeficientes é triangular superior,

$$
A = \begin{bmatrix} A_{00} & A_{01} & A_{02} \\ A_{10} & A_{11} & A_{12} \\ A_{20} & A_{21} & A_{22} \end{bmatrix}
= \begin{bmatrix} -3 & 4 & -1 \\ 0 & 3 & 2 \\ 0 & 0 & 3 \end{bmatrix},\quad\quad\quad\quad b = \begin{bmatrix} b_0 \\ b_1 \\ b_2 \end{bmatrix} = \begin{bmatrix} 4 \\ -1 \\ -15 \end{bmatrix}.
$$

<br>

Ora, utilizando a terceira equação, é simples obter o valor de $x_2$:

$$
3x_2 = -15 \quad\quad \implies \quad\quad x_2= -5.
$$

<br>

Assim, podemos determinar $x_1$ e posteriormente $x_0$:

$$
3x_1 + 2x_2 = -1 \quad\quad \implies\quad\quad  x_1 = \frac{-1-2x_2}{3} \quad\quad \implies\quad\quad  x_1 = \frac{-1-2\cdot (-5)}{3} \quad\quad \implies\quad\quad  x_1 = 3
$$

e

$$
-3x_0 + 4x_1 -x_2 = 4 \quad\quad \implies \quad\quad x_0 = \frac{4-4x_1 + x_2}{-3} \quad\quad \implies \quad\quad x_0 = \frac{4-4\cdot 3 + (-5)}{-3} \quad\quad \implies \quad\quad x_0 = \frac{13}{3}.
$$

<br>

Vamos implementar esses cálculos computacionalmente.

Começamos definindo as matrizes.

In [ ]:
A = np.array([[-3, 4, -1],
              [0, 3, 2],
              [0, 0, 3]])
b = np.array([4, -1, -15])

# inicializando x com três entradas nulas, a serem atualizadas posteriormente
x = np.zeros(3)

print(A)
print()
print(b)
print()
print(x)

[[-3  4 -1]
 [ 0  3  2]
 [ 0  0  3]]

[  4  -1 -15]

[0. 0. 0.]


<br> Começamos com a terceira equação, que é da forma

$$
A_{22}x_2 = b_2.
$$

Logo, isolamos $x_2$.

In [ ]:
# defina x[2] em função de b[2] e A[2, 2]
x[2] = b[2]/A[2,2]

# assim, a terceira entrada de x é atualizada
print(x)

[ 4.33333333  3.         -5.        ]


<br> Note que a segunda equação é dada por

$$
A_{11}x_1 + A_{12}x_2 = b_1.
$$

Então isolamos $x_1$ em termos dos coeficientes de $A$, de $b_1$ e de $x_2$:

In [ ]:
# determine x[1] isolando-o na equação acima
x[1] = (b[1]-2*x[2])/(A[1,1])

print(x)

[ 4.33333333  3.         -5.        ]


<br> A seguir, fazemos o mesmo com $x_0$, dado pela equação

$$
A_{00}x_0 + A_{01}x_1 + A_{02}x_2 = b_0.
$$

In [ ]:
x[0] = (b[0] - 4*x[1] + x[2])/A[0,0]

print(x)

[ 4.33333333  3.         -5.        ]


<br> Confirmando que o vetor `x` definido é solução do sistema:

In [ ]:
print(A.dot(x) == b)

[False  True  True]


<br><br>

***

## Exercício 2: <br>

Generalize o raciocínio acima e defina computacionalmente uma função `solve_triang_3`, cujas entradas são as matrizes $A$ e $b$ que descrevem um sistema linear $3\times 3$ triangular qualquer e que retorne a solução $x$.

Teste a função com o sistema estudado acima.

In [ ]:
A = np.array([[-3, 4, -1],
              [0, 3, 2],
              [0, 0, 3]])

b = np.array([4, -1, -15])

def solve_triang_3(A, b):
  x[2] = b[2]/A[2,2]
  x[1] = (b[1] - A[1, 2]*x[2])/(A[1, 1])
  x[0] = (b[0] - A[0, 1]*x[1] + A[0, 2]*x[2])/(A[0, 0])
  return x

print(x)

[ 4.33333333  3.         -5.        ]


<br><br>

***

## Exercício 3: <br>

(a) Generalize a função acima a uma função `solve_triang_4`, que resolve um sistema linear de dimensão $4\times 4$ triangular qualquer.

In [ ]:
#z=x[3], y=x[2], x=x[1], v = x[0]

from re import X
def solve_triang_4(A, b):

  x[3] = b[3]/A[3, 3]
  x[2] = (b[2] - (A[2, 3])*x[3])/(A[2,2])
  x[1] = (b[1] - (A[1, 2]*x[2]) - (A[1, 3]*x[3]))/(A[1, 1])
  x[0] = (b[0] - (A[0, 1]*x[1]) - (A[0, 2]*x[2]) - (A[0, 3]*x[3]))/(A[0, 0])
  return x


<br>

(b) Utilize a função acima para determinar a solução de  

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
-2x_1 + 4x_2 + 5x_3 = -3 \\
x_2 + 4x_3 = 1 \\
3x_3 = 2
\end{cases}.
$$

Faça a prova real multiplicando $Ax$ e iguale a $b$ para verificar o algoritmo.

In [ ]:
# resolva aqui

A = np.array([[-2, 3, -1, 1],
      [0, -2, 4, 5],
      [0, 0, 1, 4],
      [0, 0, 0, 3]])

b = np.array([2, -3, 1, 2])

def solve_triang_4(A, b):
  x = np.zeros(4)
  x[3] = b[3]/A[3, 3]
  x[2] = (b[2] - A[2, 3]*x[3])/A[2,2]
  x[1] = (b[1] - A[1, 2]*x[2] - A[1, 3]*x[3])/A[1, 1]
  x[0] = (b[0] - A[0, 1]*x[1] - A[0, 2]*x[2] - A[0, 3]*x[3])/A[0, 0]
  return x

print(solve_triang_4(A, b))

[-0.08333333 -0.16666667 -1.66666667  0.66666667]


<br><br>

***

# Resolvendo sistemas triangulares de dimensão arbitrária <br>

Nosso próximo passo é resolver um sistema triangular de dimensão qualquer.

Para isso, precisaremos generalizar as funções anteriores para lidar com sistemas com $n$ equações e $n$ incógnitas,

$$
\begin{cases}
A_{00}x_0\ + &A_{01}x_1\ + &A_{02}x_2\ + &\cdots\ + &A_{0n}x_n = b_0\\
&A_{11}x_1\ + &A_{12}x_2\ + &\cdots\ + &A_{1n}x_n = b_1\\
&&A_{22}x_2\ + &\cdots\ + &A_{2n}x_n = b_2\\
&&\ \ \ \vdots&\\
&&&&A_{nn}x_n = b_n
\end{cases}
$$


cuja matriz de coeficientes e matriz de termos independentes são do tipo

$$A = \begin{bmatrix}
	         A_{00} & A_{01} & A_{02} & \cdots & A_{0n}\\
	         0      & A_{11} & A_{12} & \cdots & A_{1n}\\
	         0      & 0      & A_{22} & \cdots & A_{2n}\\
	         \vdots & \vdots & \vdots & \vdots & \vdots\\
	         0      & 0      & 0      &  0     & A_{nn}
	         \end{bmatrix}, \quad\quad\quad b = \begin{bmatrix} b_0 \\ b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix}.$$
             
Para isso, usamos os seguintes passos:

1. Determinamos o valor de $x_n$: $\quad x_n = \frac{b_n}{A_{n,n}}$

2. Determinamos o valor de $x_{n-1}$: $\quad x_{n-1} = \frac{b_{n-1}\ -\ A_{n-1, n}x_n}{A_{n-1,n-1}}$

3. Determinamos o valor de $x_{n-2}$: $\quad x_{n-2} = \frac{b_{n-2}\ -\ A_{n-2, n-1}x_{n-1}\ -\ A_{n-2, n}x_n}{A_{n-2,n-2}} = \frac{b_{n-2}\ -\ \sum_{i = {n-1}}^n A_{n-2, i}x_i}{A_{n-2,n-2}} $

   $\vdots$

$\ \ $ n. Determinamos o valor de $x_0$: $\quad x_0 = \frac{b_0\ -\ \sum_{i=1}^n A_{0, i}x_{i}}{A_{00}}$.

<br><br>

Note que o $k$-ésimo coeficiente, $x_k$, é dado por

$$
x_k = \frac{b_{k}\ -\ \sum_{i = k+1}^n A_{k, i}x_i}{A_{k,k}}.
$$

<br>

O algoritmo acima pode ser implementado computacionalmente usando um laço `for` da seguinte maneira:

In [ ]:
# comente cada linha do código abaixo, detalhando o que ela faz (se necessário,
# use outra célula de código como rascunho e explore os comandos que você não
# conhece)

def solve_diag_n(A, b):
    # comente
    n = len(A)
    # comente
    x = np.zeros(n)
    # comente
    for k in range(n-1, -1, -1):
        # comente
        soma = 0
        # comente
        for i in range(k + 1, n):
            soma = soma + complete_aqui
        # comente
        x[k] = complete_aqui
    return x

<br><br>

***

## Exercício 4: <br>

Defina uma matriz **triangular** $A$ $6\times 6$ qualquer e um vetor $b\in\mathbb R^6$ e use a função acima para resolver o sistema $Ax = b$. Utilize a função `np.linalg.solve` para confirmar sua resposta.

In [ ]:
# resolva aqui