<a href="https://colab.research.google.com/github/Gus-22/Gus-22/blob/main/4_operacoes_elementares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u><center>**Operações elementares**</center></u>

<br>

Na aula passada, vimos como resolver sistemas lineares **triangulares**.

<br>

A pergunta que fica é:

> **Como lidar com sistemas $n\times n$ não-triangulares?**

<br>

Uma possível resposta é **transformar o sistema de modo a obter um sistema triangular com o mesmo conjunto solução**.

<br>

Fica a pergunta:

> **Quais operações simplificam um sistema linear, mas preservam o seu conjunto solução?**

<br>

Estudando o assunto, chegamos a três **operações elementares**. Vejamos cada uma.

<br>

***


# <center>Trocar duas equações de lugar</center>

<br>

Claramente, a ordem com que as equações aparecem em um sistema não interfere na solução do sistema em si. Ou seja, o sistema

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
3x_0-2x_1 + 4x_2 + 5x_3 = -3 \\
7x_0 - 4x_1 + x_2 + 4x_3 = 1 \\
x_0 - 4x_2 +3x_3 = 2
\end{cases}
$$

possui a mesma solução do sistema abaixo, obtido simplesmente trocando a segunda e a quarta equações de lugar,

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
x_0 - 4x_2 +3x_3 = 2 \\
7x_0 - 4x_1 + x_2 + 4x_3 = 1 \\
3x_0-2x_1 + 4x_2 + 5x_3 = -3
\end{cases}.
$$

<br>

## Exercício 1:

Verifique computacionalmente a afirmação acima, construindo as matrizes correspondentes a cada um dos sistema e resolvendo-os com a função `np.linalg.solve`.

In [ ]:
import numpy as np

A1 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])
A2 = np.array([[-2, 3, -1, 1], [1, 0, -4, 3], [7, -4, 1, 4], [3, -2, 4, 5]])
b1 = np.array([2, -3, 1, 2])
b2 = np.array([2, 2, 1, -3])

In [ ]:
# função que calcula a resposta da matriz A1 com termos independentes b1
res = np.linalg.solve(A1, b1)

print(res)

[ 1.29924242  1.50757576 -0.47348485 -0.39772727]


In [ ]:
# função que calcula a resposta da matriz A2 com termos independentes b2
res = np.linalg.solve(A2, b2)

print(res)

[ 1.29924242  1.50757576 -0.47348485 -0.39772727]


**Conclusão:** comprovado que inverter a ordem das linhas da matriz não altera o conjunto solução.

<br>

## Exercício 2:

(a) Defina abaixo uma função `troca_linhas`, que recebe como entrada um *array* V qualquer e os índices de duas linhas, $i$ e $j$, e devolva outro *array* $W$, obtido de $V$ ao trocar de lugar a linha $i$ pela linha $j$.

In [ ]:
def troca_linhas(V, i, j):
  # a linha abaixo cria uma matriz W com o mesmo formato de V
  W = np.zeros(np.shape(V))
  # n é o número de linhas da matriz
  n = len(V)
  # laço for que passa por cada linha de W
  for k in range(n):
    # se o indice k for igual a i, copiamos a linha j de V para a linha k de W
    if k == i:
      W[k] = V[j]
    # se o indice k for igual a j, copiamos a linha i de V para a linha k de W
    elif k == j:
      W[k] = V[i]
    # para todas as outras linhas, copiamos V direto para W
    else:
      W[k] = V[k]
  return W

<br>

(b) Teste a função definida acima com os *arrays* definidos no Exercício 1. Isto é, usa a função para trocar as linhas da *array* inicial e compare com a *array* definida manualmente com as linhas trocadas.

In [ ]:
# a função troca a linha 1 e 3 da matriz V
V = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])

print(troca_linhas(V, 1, 3))

[[-2.  3. -1.  1.]
 [ 1.  0. -4.  3.]
 [ 7. -4.  1.  4.]
 [ 3. -2.  4.  5.]]


<br><br>

***

<br>

# <center>Multiplicar uma equação por uma constante diferente de zero</center>
<br>

Analogamente, ao multiplicarmos ambos os lados de uma equação por uma constante não-nula obtemos outra equação equivalente à primeira.

Assim, o sistema

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
3x_0-2x_1 + 4x_2 + 5x_3 = -3 \\
7x_0 - 4x_1 + x_2 + 4x_3 = 1 \\
x_0 - 4x_2 +3x_3 = 2
\end{cases}
$$

possui a mesma solução do sistema abaixo, obtido simplesmente multiplicando a terceira equação por -3,

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
3x_0-2x_1 + 4x_2 + 5x_3 = -3 \\
-21x_0 +12x_1 -3x_2 -12x_3 = -3 \\
x_0 - 4x_2 +3x_3 = 2
\end{cases}.
$$

<br>

## Exercício 3:

Verifique a afirmação acima definindo as matrizes de cada sistema como *arrays* e resolvendo cada sistema com o comando `np.linalg.solve`.

In [ ]:
#definindo a matriz A1 e os coeficientes b1
A1 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])
b1 = np.array([2, -3, 1, 2])

#usando linalg para achar a solução
resp = np.linalg.solve(A1, b1)
print(resp)

[ 1.29924242  1.50757576 -0.47348485 -0.39772727]


In [ ]:
#definindo a mesma matriz com a linha 2 multiplicada por -3
A2 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [-21, 12, -3, -12], [1, 0, -4, 3]])
b2 = np.array([2, -3, -3, 2])

#usando linalg para ver que a solução será a mesma
resp = np.linalg.solve(A2, b2)
print(resp)

[ 1.29924242  1.50757576 -0.47348485 -0.39772727]


<br>

## Exercício 4:

(a) Defina abaixo uma função `multiplica_linha`, que recebe como entrada um *array* V qualquer, o índice de uma linha, $i$, e uma constante não-nula, $t$, e devolva outro *array* $W$, obtido de $V$ ao multiplicar a $i$-ésima linha por $t$.

In [ ]:
def multiplica_linha(V, i, t):
  #criando uma matriz W com o mesmo formato de V
  W = np.zeros(np.shape(V))
  #n é o número de linhas da matriz
  n = len(V)
  # laço for que passa por cada linha de W
  for k in range(n):
    #copia a linha i de V para a linha i de W multiplicada pela constante t
    W[i] = V[i] * t
    if k != i: #se k for diferente da linha i que vai ser substituida, é pra copiar igual
      W[k] = V[k]
  return W

<br>

(b) Teste a função definida acima com os *arrays* definidos no Exercício 3. Isto é, usa a função para multiplicar a linha da *array* inicial e compare com a *array* definida manualmente com a linha multiplicada.

In [ ]:
#definindo a matriz
A1 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])

#checando que a função faz a mesma operação de multiplicar a linha dois por -3
res = multiplica_linha(A1, 2, -3)
print(res)

[[ -2.   3.  -1.   1.]
 [  3.  -2.   4.   5.]
 [-21.  12.  -3. -12.]
 [  1.   0.  -4.   3.]]


<br><br>

***

<br>

# <center>Substituir uma equação por uma ela mesma mais um múltiplo de outra equação</center>
<br>

A terceira operação elementar consiste em substituir uma equação do sistemas por ela somada a uma múltipla de outra equação.

Por exemplo, no sistema

$$
\begin{cases}
-2x_0 + 3x_1 -x_2 + x_3 = 2 \\
3x_0 -2x_1 + 4x_2 + 5x_3 = -3 \\
7x_0 - 4x_1 + x_2 + 4x_3 = 1 \\
x_0 - 4x_2 +3x_3 = 2
\end{cases}
$$

podemos substituir a primeira linha $L_0$ por $L_0 +2L_3$, obtendo os sistema

$$
\begin{cases}
3x_1 -9x_2 + 7x_3 = 6 \\
3x_0 -2x_1 + 4x_2 + 5x_3 = -3 \\
7x_0 - 4x_1 + x_2 + 4x_3 = 1 \\
x_0 - 4x_2 +3x_3 = 2
\end{cases},
$$
que possui a mesma solução do primeiro.

<br>

## Exercício 5:

Verifique a afirmação acima definindo as matrizes de cada sistema como *arrays* e resolvendo cada sistema com o comando `np.linalg.solve`.

In [ ]:
#definindo as matrizes e os termos independentes
A1 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])
b1 = np.array([2, -3, 1, 2])

A2 = np.array([[0, 3, -9, 7], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])
b2 = np.array([6, -3, 1, 2])

#usando linalg para achar a solução das matrizes
resp1 = np.linalg.solve(A1, b1)
resp2 = np.linalg.solve(A2, b2)

#verificando que a solução é a mesma com a substituição de linhas L0 = L0 + 2L3
print("Solução do sistema original:")
print(resp1)

print("\nSolução do sistema modificado:")
print(resp2)

Solução do sistema original:
[ 1.29924242  1.50757576 -0.47348485 -0.39772727]

Solução do sistema modificado:
[ 1.29924242  1.50757576 -0.47348485 -0.39772727]


<br>

## Exercício 6:

(a) Defina abaixo uma função `substitui_linha` que efetua a operação acima de maneira genérica.

In [ ]:
def substitui_linha(V, i, j, t):
  # cria uma matriz W com o mesmo formato de V
  W = np.zeros(np.shape(V))
  # n é o número de linhas da matriz
  n = len(V)
  # laço for que passa por cada linha de W
  for k in range(n):
    # se k for igual a linha que queremos substituir, k é igual a k + outra linha vezes a constante
    if k == i:
      W[k] = V[k] + V[j] * t
    else:  # se k não for a linha que queremos substituir, apenas copia igual
      W[k] = V[k]
  return W

<br>

(b) Teste a função definida acima com os *arrays* definidos no Exercício 5. Isto é, usa a função para substituir a linha da *array* inicial e compare com a *array* definida manualmente com a linha substituída.

In [ ]:
#definindo a matriz inicial
A1 = np.array([[-2, 3, -1, 1], [3, -2, 4, 5], [7, -4, 1, 4], [1, 0, -4, 3]])
b1 = np.array([2, -3, 1, 2])

#fazendo L0 = L0 + 2L3
res = substitui_linha(A1, 0, 3, 2)
print(res)

[[ 0.  3. -9.  7.]
 [ 3. -2.  4.  5.]
 [ 7. -4.  1.  4.]
 [ 1.  0. -4.  3.]]


**Conclusão:** observamos que a resposta utilizando a função substitui_linha foi igual a resposta fazendo o método manualmente.